locations=[
 ('bay area,usa','Bay Area, USA'),
 ('palo alto,bay area,california,usa','Palo Alto,Bay Area,California,USA'),
 ('san francisco,bay area,california,usa','San francisco,Bay area,California,USA'),
 ('mountain view,bay area,california,usa','Mountain View,Bay area,California,USA'),
 ('la,california,usa','LA,California,USA'),
 ('new york,usa','New York,USA'),
 ('nyc,new york,usa','NYC,New York,USA'),
 ('seattle,usa','Seattle,USA'),
 ('chicago,usa','Chicago,USA'),
 ('austin,texas,us','Austin,Texas,USA'),
 ('portland,oregon,usa','Portland,Oregon,USA'),
 ('singapore','Singapore'),
 ('tokyo,japan','Tokyo, Japan'),
 ('uk','UK'),
 ('london,uk','London,UK'),
 ('ireland','Ireland'),
 ('dublin,ireland','Dublin,Ireland'),
 ('france','France'),
 ('berlin,germany','Berlin,Germany'),
 ('sweden','Sweden'),
 ('israel','Israel'),
 ('dubai','Dubai'),
 ('latvia','Latvia'),

 ('moscow,russia','Moscow, Russia'),
 ('warsaw,poland','Warsaw,Poland'),
 ('casablanca,morocco','Casablanca,Morocco'),
 ('australia','Australia'),
 ('india','India'),
 ('gurgaon,india','Gurgaon,India'),
 ('mumbai,india','Mumbai,India'),
 ('bangalore,india','Bangalore,India'),
 ('hyderabad,india','Hyderabad,India'),
 ('thailand','Thailand'),
 ('bangkok,thailand','Bangkok,Thailand'),
 ('Jarkata,Indonesia','Jarkata,Indonesia'),
 ('ho chi minh,vietnam','Ho Chi Minh,Vietnam'),
 ('kuala lumpar,malaysia','Kuala Lumpar,Malaysia'),
 ('china','China'),
 ('beijing,china','Beijing,China'),
 ('shanghai,china','Shanghai,China'),
 ('sydney,australia','Sydney,Australia'),
 ('nanjing,china','Nanjing,China'),
 ('zhejiang,china','Zhejiang,China'),
 ('shenzhen,china','Shenzhen,China'),
 ('jiangsu,china','Jiangsu,China'),
 ('wuhan,hubei,china','Wuhan,Hubei,China'),
 ('hong kong','Hong Kong'),
 ('russia','Russia'),
 ('poland','Poland'),
 ('brazil','Brazil'),
 ('sao paulo,brazil','Sao paulo,brazil'),
 ('japan','Japan')]