# Generated by Django 3.1.1 on 2020-09-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
