# Generated by Django 3.1.1 on 2020-09-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20200923_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
