# Generated by Django 3.1.1 on 2020-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20200925_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='recruiter',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
