# Generated by Django 3.0.5 on 2020-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_candidateedu_candidateexperience_candidateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='resume_content',
            field=models.TextField(default=None),
        ),
    ]
