# Generated by Django 3.0.5 on 2020-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_candidateinfo_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='hunter',
            field=models.CharField(default=None, max_length=264),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='resume_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
