# Generated by Django 3.0.5 on 2020-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200917_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='hunter',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
