# Generated by Django 3.1.1 on 2020-09-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_candidateedu_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateedu',
            name='degree',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateedu',
            name='end_date',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateedu',
            name='major',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateedu',
            name='start_date',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateedu',
            name='university',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='company',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='position',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='start_date',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='applied_location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='area_of_focus',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='bytedance_application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='bytedance_application_position',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='hunter',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='leadership_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='related_work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='resume_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='resume_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content_requst', models.CharField(max_length=512, null=True)),
                ('applied_positon_request', models.CharField(max_length=512, null=True)),
                ('recent_work_request', models.CharField(max_length=512, null=True)),
                ('titles_request', models.CharField(max_length=512, null=True)),
                ('companies_request', models.CharField(max_length=264, null=True)),
                ('location_request', models.CharField(max_length=264, null=True)),
                ('min_work_length_request', models.IntegerField(null=True)),
                ('max_work_length_request', models.IntegerField(null=True)),
                ('min_leadership_length_request', models.IntegerField(null=True)),
                ('max_leadership_length_request', models.IntegerField(null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
