# Generated by Django 3.1.1 on 2020-09-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200922_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='account_manager',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
