# Generated by Django 3.1.1 on 2020-09-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200923_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='company',
        ),
        migrations.RenameField(
            model_name='candidateinfo',
            old_name='bytedance_application_position',
            new_name='applied_position',
        ),
        migrations.DeleteModel(
            name='ClientCompany',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
    ]
