# Generated by Django 3.1.1 on 2020-09-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20200925_0336'),
        ('articles', '0014_auto_20200925_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_experience', models.BooleanField()),
                ('status', models.CharField(max_length=64)),
                ('resume_submited_date', models.DateTimeField()),
                ('applied_company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='positions.client')),
                ('applied_position', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='positions.position')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.candidateinfo')),
            ],
        ),
    ]
