# Generated by Django 3.1.1 on 2020-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200925_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatus',
            name='resume_submited_date',
            field=models.DateField(),
        ),
    ]
