# Generated by Django 3.1.1 on 2020-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200925_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='resume_submited_date',
            field=models.CharField(max_length=64),
        ),
    ]
