# Generated by Django 3.1.1 on 2020-09-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20200925_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatestatus',
            old_name='applied_position',
            new_name='client_position',
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
