# Generated by Django 3.1.1 on 2020-09-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20200925_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatus',
            name='resume_submited_date',
            field=models.DateField(),
        ),
    ]
