# Generated by Django 3.1.1 on 2020-09-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20200926_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
